/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gudenau_nx_ptree_util_FileHelper */

#ifndef _Included_net_gudenau_nx_ptree_util_FileHelper
#define _Included_net_gudenau_nx_ptree_util_FileHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_gudenau_nx_ptree_util_FileHelper
 * Method:    read
 * Signature: (IJJI)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_util_FileHelper_read
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
