/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gudenau_nx_ptree_usb_LibUsb */

#ifndef _Included_net_gudenau_nx_ptree_usb_LibUsb
#define _Included_net_gudenau_nx_ptree_usb_LibUsb
#ifdef __cplusplus
extern "C" {
#endif
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_CAP_HAS_HOTPLUG
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_CAP_HAS_HOTPLUG 1L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_HOTPLUG_EVENT_DEVICE_ARRIVED
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_HOTPLUG_EVENT_DEVICE_ARRIVED 1L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_HOTPLUG_EVENT_DEVICE_LEFT
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_HOTPLUG_EVENT_DEVICE_LEFT 2L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_SUCCESS
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_SUCCESS 0L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_IO
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_IO -1L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_INVALID_PARAM
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_INVALID_PARAM -2L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_ACCESS
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_ACCESS -3L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NO_DEVICE
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NO_DEVICE -4L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NOT_FOUND
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NOT_FOUND -5L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_BUSY
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_BUSY -6L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_TIMEOUT
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_TIMEOUT -7L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_OVERFLOW
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_OVERFLOW -8L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_PIPE
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_PIPE -9L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_INTERRUPTED
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_INTERRUPTED -10L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NO_MEM
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NO_MEM -11L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NOT_SUPPORTED
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_NOT_SUPPORTED -12L
#undef net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_OTHER
#define net_gudenau_nx_ptree_usb_LibUsb_LIBUSB_ERROR_OTHER -99L
/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_init
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1exit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_get_device_list
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1get_1device_1list
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_free_device_list
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1free_1device_1list
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_ref_device
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1ref_1device
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_unref_device
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1unref_1device
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_open
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1open
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_claim_interface
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1claim_1interface
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_get_device_descriptor
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1get_1device_1descriptor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_bulk_transfer
 * Signature: (JBJIJI)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1bulk_1transfer
  (JNIEnv *, jclass, jlong, jbyte, jlong, jint, jlong, jint);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_hotplug_register_callback
 * Signature: (JIIIIIJJJ)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1hotplug_1register_1callback
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_hotplug_deregister_callback
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1hotplug_1deregister_1callback
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_has_capability
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1has_1capability
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_handle_events_completed
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1handle_1events_1completed
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bLength
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bDescriptorType
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bDescriptorType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bcdUSB
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bcdUSB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bDeviceClass
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bDeviceClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bDeviceSubClass
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bDeviceSubClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bDeviceProtocol
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bDeviceProtocol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bMaxPacketSize0
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bMaxPacketSize0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_idVendor
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1idVendor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_idProduct
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1idProduct
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bcdDevice
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bcdDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_iManufacturer
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1iManufacturer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_iProduct
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1iProduct
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_iSerialNumber
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1iSerialNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    libusb_device_descriptor_bNumConfigurations
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_libusb_1device_1descriptor_1bNumConfigurations
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    getHotplugCallback
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_getHotplugCallback
  (JNIEnv *, jclass);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    createHotplugData
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_createHotplugData
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     net_gudenau_nx_ptree_usb_LibUsb
 * Method:    freeHotplugData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_nx_ptree_usb_LibUsb_freeHotplugData
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
